[misc]
pre_sudo = true
assume_yes = true
disable = ["firmware"]
cleanup = true
notify_end = "on_failure"

[linux]
arch_package_manager = "paru"

[firmware]
# Only show available firmware updates, do not flash anything
upgrade = false

[git]
max_concurrency = 5

[custom_commands]
"Sync dotfiles" = "~/dotfiles/scripts/sync.sh"
